### ISSUE TITLE
Connections property issue

### ISSUE THREAD

**Issue by madhus-ch** [axtension/contentgate-samples#1]
Getting issue in Program.cs after copying the code in VS:
// add the connection to one or more business entities.
                    Connections =
                    {
                        // directly linked business entity reference (using Content Gate id)
                        20392,
                        // externally linked business entity reference (using external reference) which means:
                        // business entity connector reference, external type, external id combination
                        **("DYN365", "Customers", "CustomerAccount='US-023',dataAreaId='usmf'")**
                    }

The issue is with inside the connections. In our case, we targeted to Products. Error message is "Cannot convert string to IList<AXtension.xxxxx.xxx.BusinessEntities>. Please help me to resolve the issue.

**Comment by JoepKillaars** [comment]
I will look into this and come back to you with an answer.

**Comment by JoepKillaars** [comment]
I was unable to reproduce the issue using the demo code provided in this repository. Can you please share some more details on the error ? Is it a runtime issue or a compile time issue? What are the exact values you provide. If you are unable to share details, can you provide a mockup of the data?

**Comment by madhus-ch** [comment]
I am getting compile time issue. The exact issue is with setting the Connections value. Please see the attached files. The file "1.jpg" refers to error in Connections value setting. And "2.jpg" refers to Connections property is having only get but no set. Is this is due to my .Net framework is 4.6.2?
What is the .Net framework that I should use for not getting this issue?

![1](https://user-images.githubusercontent.com/38136418/46071786-6f3c0c80-c19e-11e8-98b1-01a7b1024012.jpg)
![2](https://user-images.githubusercontent.com/38136418/46071788-6f3c0c80-c19e-11e8-92a9-4987dc5d97ab.jpg)

**Comment by JoepKillaars** [comment]
Ah yes, I did not know you were running 4.6.1

Probably the Tuple type is not supported in your project. Can you please try and just create an instance of te BusinessEntityRef using the new keyword ? This should fix it. 

The shorthand provided in the samples is using .net4.7.1 and is using the tuple type as an implicit conversion type for the ref type.

Please let me know if this works for you.

**Comment by madhus-ch** [comment]
Can't create instance for BusinessEntityRef as it is abstract class.

Can I get the code and DLL which supports VS 2015 / V4.6.1 ? Please help me..

**Comment by JoepKillaars** [comment]
I am sorry for some delays in repsonse. I am in the US this week. 

I am not cleared to give you our source code, however, you can look into the assembly using the VS object explorer or through reflector (or similar program).

The advice I gave you, was made without looking at our code, I have looked into it and the class is indeed abstract, however the classes to use.

Thre are two ways of constructing an instance of the business entity ref: 

For direct reference
`BusinessEntityRef.DirectReference(1)`

For external reference
`BusinessEntityRef.ExternalReference("connector", "externalType", "externalId")`

I hope this helps. If you need any more immediate assistance, you can always contact support@axtension.com. I will keep monitoring this issue from the US, but am not always able to reply immediately.

Hope this helps you out.
